CREATE DATABASE db_camagru;
CREATE TABLE tb_users
(
	id INT PRIMARY KEY UNIQUE NOT NULL AUTO_INCREMENT,
	username VARCHAR(20) UNIQUE NOT NULL,
	password TEXT NOT NULL,
	email VARCHAR(254) UNIQUE NOT NULL,
	admin BOOLEAN DEFAULT '0',
	verified TEXT,
)
